// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-my-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-my-events.ts
var list_my_events_default = defineTool({
  name: "list_my_events",
  title: "List my events",
  description: "List events the signed-in user is hosting or attending, with RSVP status.",
  inputSchema: {
    limit: z.number().int().optional().describe("Max events to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const [hosted, guested] = await Promise.all([
      supabase.from("events").select("id, code, title, vibe, location, date_time, host_id").eq("host_id", userId).order("date_time", { ascending: true }).limit(max),
      supabase.from("event_guests").select("rsvp_status, events(id, code, title, vibe, location, date_time, host_id)").eq("user_id", userId).limit(max)
    ]);
    if (hosted.error) return { content: [{ type: "text", text: hosted.error.message }], isError: true };
    if (guested.error) return { content: [{ type: "text", text: guested.error.message }], isError: true };
    const items = [
      ...(hosted.data ?? []).map((e) => ({ ...e, role: "host", rsvp_status: null })),
      ...(guested.data ?? []).filter((g) => g.events).map((g) => ({ ...g.events, role: "guest", rsvp_status: g.rsvp_status }))
    ];
    const seen = /* @__PURE__ */ new Set();
    const events = items.filter((e) => seen.has(e.id) ? false : (seen.add(e.id), true)).slice(0, max);
    return {
      content: [{ type: "text", text: JSON.stringify(events, null, 2) }],
      structuredContent: { events }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Get full details for one event by its share code, including guest list and RSVP counts.",
  inputSchema: {
    code: z2.string().trim().describe("The event share code, e.g. ABC123.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: event, error } = await supabase.from("events").select("id, code, title, vibe, location, date_time, dress_code, extra, capacity, rsvp_deadline, host_id").eq("code", code.toUpperCase()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!event) return { content: [{ type: "text", text: `No event found with code ${code}` }], isError: true };
    const { data: guests } = await supabase.from("event_guests").select("user_id, rsvp_status").eq("event_id", event.id);
    const counts = (guests ?? []).reduce((acc, g) => {
      const key = g.rsvp_status ?? "pending";
      acc[key] = (acc[key] ?? 0) + 1;
      return acc;
    }, {});
    const result = {
      ...event,
      is_host: event.host_id === ctx.getUserId(),
      guest_count: guests?.length ?? 0,
      rsvp_counts: counts
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { event: result }
    };
  }
});

// src/lib/mcp/tools/set-rsvp.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var set_rsvp_default = defineTool3({
  name: "set_rsvp",
  title: "Set my RSVP",
  description: "Set the signed-in user's RSVP status for an event identified by its share code.",
  inputSchema: {
    code: z3.string().trim().describe("The event share code."),
    status: z3.enum(["yes", "no", "maybe"]).describe("RSVP status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ code, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: event, error: eventError } = await supabase.from("events").select("id, title").eq("code", code.toUpperCase()).maybeSingle();
    if (eventError) return { content: [{ type: "text", text: eventError.message }], isError: true };
    if (!event) return { content: [{ type: "text", text: `No event found with code ${code}` }], isError: true };
    const { data: existing } = await supabase.from("event_guests").select("id").eq("event_id", event.id).eq("user_id", userId).maybeSingle();
    const { error } = existing ? await supabase.from("event_guests").update({ rsvp_status: status }).eq("id", existing.id) : await supabase.from("event_guests").insert({ event_id: event.id, user_id: userId, rsvp_status: status });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `RSVP set to "${status}" for ${event.title}.` }],
      structuredContent: { event_id: event.id, rsvp_status: status }
    };
  }
});

// src/lib/mcp/tools/list-event-chat.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_event_chat_default = defineTool4({
  name: "list_event_chat",
  title: "List event chat",
  description: "Read recent chat messages posted on an event, newest last.",
  inputSchema: {
    code: z4.string().trim().describe("The event share code."),
    limit: z4.number().int().optional().describe("Max messages to return (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ code, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 30, 1), 100);
    const { data: event } = await supabase.from("events").select("id").eq("code", code.toUpperCase()).maybeSingle();
    if (!event) return { content: [{ type: "text", text: `No event found with code ${code}` }], isError: true };
    const { data, error } = await supabase.from("comments").select("id, user_name, text, created_at").eq("event_id", event.id).order("created_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const messages = (data ?? []).slice().reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(messages, null, 2) }],
      structuredContent: { messages }
    };
  }
});

// src/lib/mcp/tools/post-event-chat.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var post_event_chat_default = defineTool5({
  name: "post_event_chat",
  title: "Post event chat message",
  description: "Post a chat message to an event as the signed-in user.",
  inputSchema: {
    code: z5.string().trim().describe("The event share code."),
    text: z5.string().trim().describe("Message text to post.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ code, text }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!text.trim()) {
      return { content: [{ type: "text", text: "Message text cannot be empty." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: event } = await supabase.from("events").select("id").eq("code", code.toUpperCase()).maybeSingle();
    if (!event) return { content: [{ type: "text", text: `No event found with code ${code}` }], isError: true };
    const { data: profile } = await supabase.from("profiles").select("name").eq("user_id", userId).maybeSingle();
    const { data, error } = await supabase.from("comments").insert({
      event_id: event.id,
      user_id: userId,
      user_name: profile?.name ?? ctx.getUserEmail() ?? "Guest",
      text: text.trim()
    }).select("id, user_name, text, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Posted: ${text.trim()}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/create-event.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
function makeCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  return Array.from({ length: 6 }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
}
var create_event_default = defineTool6({
  name: "create_event",
  title: "Create an event",
  description: "Create a new event hosted by the signed-in user and return its share code.",
  inputSchema: {
    title: z6.string().trim().describe("Event name."),
    date_time: z6.string().trim().describe("Event start as an ISO 8601 timestamp, e.g. 2026-06-05T19:00:00Z."),
    location: z6.string().trim().optional().describe("Venue or address."),
    vibe: z6.string().trim().optional().describe("Short vibe or description line."),
    dress_code: z6.string().trim().optional().describe("Dress code / theme."),
    extra: z6.string().trim().optional().describe("Notes from the host.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, date_time, location, vibe, dress_code, extra }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const when = new Date(date_time);
    if (Number.isNaN(when.getTime())) {
      return { content: [{ type: "text", text: "date_time must be a valid ISO 8601 timestamp." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("events").insert({
      host_id: ctx.getUserId(),
      code: makeCode(),
      title: title.trim(),
      date_time: when.toISOString(),
      location: location?.trim() ?? null,
      vibe: vibe?.trim() ?? null,
      dress_code: dress_code?.trim() ?? null,
      extra: extra?.trim() ?? null
    }).select("id, code, title, date_time, location").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created "${data?.title}" \u2014 share code ${data?.code}` }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vugjjbtmcwfycqoykfgz";
var mcp_default = defineMcp({
  name: "planit-your-social-events",
  title: "Planit: Your Social Events",
  version: "0.1.0",
  instructions: "Tools for Planit, a social events app. Use `list_my_events` to see the signed-in user's events, `get_event` for details by share code, `create_event` to host a new event, `set_rsvp` to respond to an invite, and `list_event_chat` / `post_event_chat` for an event's chat.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_my_events_default,
    get_event_default,
    create_event_default,
    set_rsvp_default,
    list_event_chat_default,
    post_event_chat_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
